### ISSUE TITLE
libbrcmGLESv2.so: cannot open shared object file

### ISSUE THREAD

**Issue by DaCHack** [jhfdevelop/rpiplay_docker#1]
Hi,

I receive this error while running your image on docker, Raspberry Pi OS 32bit current version:
`./rpiplay: error while loading shared libraries: libbrcmGLESv2.so: cannot open shared object file: No such file or directory`

From my prior research this is driven by the 64bit version I used before, but this I replaced now with the current 32bit version.
In addition, I saw that there is some issue with the change from buster to bullseye.

Any chance that you could adopt the dockerfile and the image for bullseye?

Many thanks
Daniel

**Comment by jhfdevelop** [comment]
Hi, thanks for letting me know.
I might look into it next week, if I have time.

Can you tell me a little bit more about your configuration (e.g. Docker setup, OS, etc.) so I can test it?

Also, please feel free to fork this repo or open a PR if you found a solution. Since my last update on this was about 2 years ago, there is a high chance some of the forks already solved this.

Kind regards

**Comment by DaCHack** [comment]
One of the forks is me, but actually I failed due to limited knowledge. :)

I am running: Raspberry Pi OS with Linux server 5.15.32-v7l+ #1538 SMP armv7l on a Raspberry Pi 4 2GB.
Please find my Docker-compose from Portainer here:

```
version: "3.9"
services:

  rpiplay:
    image: djhofmann/rpiplay
    container_name: "rpiplay"
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/dri:/dev/dri
    volumes:
      - '/opt/vc:/opt/vc'
    environment:
      - RPI_PLAY_AUDIO="hdmi"
      - RPI_PLAY_NAME="TV"
      - RPI_PLAY_EXTRA_ARGS="-l -b auto"

```
